# Generated by Django 4.1 on 2024-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("ratings", models.FloatField()),
                ("available_rooms", models.IntegerField()),
                ("price", models.FloatField()),
                ("amenities", models.TextField()),
                ("bed_type", models.CharField(max_length=50)),
            ],
        ),
    ]
