# Generated by Django 4.1 on 2024-07-22 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotelier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
